[Features] Adds functionality for multiple datastreams, decreasing data, and reverse pipeline
BU-DiSC/bods pull request #22
Opened 2024-11-21 20:10 UTC by svuppala2006

This PR adds extensions onto the BoDs program.

- Adds functionality for multiple datastreams through args.toml file
- New python program to get workload parameters from BoDs generated data file (no alpha or beta yet)
- Adds functionality for values to be generated in decreasing order

**This PR also changes the following**:

- C++ standard 11 changed to C++ standard 17
- All unsigned longs were changed to int types
- L is now generated following a beta distribution rather than a uniform random 
- Passes only arguments of args.toml and number of partitions

2025-01-21 19:34 UTC, ramananeesh requested changes
@svuppala2006 left some comments for you to take a look at.

2025-01-21 19:34 UTC, ramananeesh commented on inverse_bods.py
Can you remind me what this file does again?

2025-01-21 19:34 UTC, ramananeesh commented on graph.py
Do we need this file to be part of bods? If yes, maybe we make it slightly more useful - e.g., taking in the workloads file as an input arg, ability to save the plot, add some input guidelines, etc.

2025-01-21 19:34 UTC, ramananeesh commented on src/args.toml
> +[[partition]]
Let's keep args.toml to generate a single stream/partition as of now. We can add sample args.toml for multiple streams + add info to the readme for more partitions.

2025-01-21 19:34 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
>  using namespace boost::math;
Just to make clear all dependencies, let's remove this line and use the namespace wherever applicable line-wise.

2025-01-21 19:34 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +                                            int Total_Numbers, int L,
though this was not introduced from changes in this branch, I think we should rename `Total_Numbers` to `total_numbers` just to maintain convention. Make all other changes as applicable.

2025-01-21 19:34 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +    int *array = new int[TOTAL_NUMBERS];
Can you remind us the reason why we moved from `unsigned long` to `int` again?

2025-01-21 19:34 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +            double randFromUnif = ((double)rand() / (RAND_MAX));
Let's establish a convention for variable names - either we use camel case or using underscore and apply this throughout the repo.

2025-01-21 19:34 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +            // int start = position - l_absolute;
remove unused code.

2025-01-21 19:34 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +            // int end = position + l_absolute;
remove unused code.

2025-01-21 19:34 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +// int pTOTAL_NUMBERS, unsigned int pdomain, int
remove this line of comment

2025-01-23 02:59 UTC, svuppala2006 commented on inverse_bods.py
This file produces the arguments for the workload descriptor from the data stream. I can rename it to something that make more sense.

2025-01-23 03:00 UTC, svuppala2006 commented on graph.py
No, we don't need to add it. This was just what I had and I automatically selecting to add all changes to the commit.

2025-01-23 03:02 UTC, ramananeesh commented on inverse_bods.py
yeah lets rename it to `estimate_k_l_from_input.py`

2025-01-23 03:03 UTC, svuppala2006 commented on src/args.toml
> +[[partition]]
Okay, then I'll just make another file that can be for multiple streams, and I'll reduce the current args.toml to just the one stream.

2025-01-23 03:03 UTC, ramananeesh commented on inverse_bods.py
Also, can we change the program to take in the file name as an argument? Use a simple interface where someone can use `-h` or `--help` to print out what is the calling format for this program and also print out the help interface if the input arguments are invalid

2025-01-23 03:07 UTC, ramananeesh commented on graph.py
I see. Feel free to remove it or stash it for the time being... We can discuss tomorrow if we need to keep it (we will make a new PR for it in case we decide to).

2025-01-23 03:10 UTC, svuppala2006 commented on src/sortedness_data_generator.cpp
> +                                            int Total_Numbers, int L,
I wrote it in the message for the PR as "All unsigned longs were changed to int types" but I'll make the change.

2025-01-23 03:19 UTC, svuppala2006 commented on src/sortedness_data_generator.cpp
> +    int *array = new int[TOTAL_NUMBERS];
I'm pretty sure there was an issue when I was making the multiple partitions feature because I couldn't perform a certain method on unsigned longs.

2025-01-23 03:20 UTC, svuppala2006 commented on src/sortedness_data_generator.cpp
> +            double randFromUnif = ((double)rand() / (RAND_MAX));
I think I'll switch everything to camel case if that's fine

2025-01-23 03:23 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +                                            int Total_Numbers, int L,
@svuppala2006 Oh I meant the variable name not the type. I think it highlighted the wrong stuff

2025-01-23 03:24 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +    int *array = new int[TOTAL_NUMBERS];
I see. We can go with int for now but let's open a new issue for checking compatibility with `unsigned long`.

2025-01-23 03:24 UTC, ramananeesh commented on src/sortedness_data_generator.cpp
> +            double randFromUnif = ((double)rand() / (RAND_MAX));
use the `_` since it is more prevalent in the code and looks cleaner.

2025-01-30 03:46 UTC, svuppala2006 commented on src/sortedness_data_generator.cpp
>  using namespace boost::math;
Does this mean you want me to add a line "using namespace toml;"? I don't really understand what you mean.

2025-01-30 04:11 UTC, svuppala2006 commented on src/sortedness_data_generator.cpp
> +// int pTOTAL_NUMBERS, unsigned int pdomain, int
I removed the entire comment

2025-02-03 14:54 UTC, ramananeesh approved these changes
LGTM 👍

2025-02-03 15:50 UTC, ephoris commented on README.md
> +   ./sortedness_data_generator -P <total partitions> -F <relative workload description path>
At some point, we should infer the number of partitions from the `args.toml` file.

2025-02-03 15:50 UTC, ephoris approved these changes
LGTM!

2025-02-03 16:06 UTC, ramananeesh commented on README.md
> +   ./sortedness_data_generator -P <total partitions> -F <relative workload description path>
Agreed. @svuppala2006 let's merge this and then create the issue once it is in `main` so we can refer to it.

2025-02-05 18:09 UTC, merged